# Database configuration
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.url=jdbc:derby:memory:willhaben-db;create=true
# Username i password nisu potrebni

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

